name: Desplegar app en GitHub Pages

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Instalar node
      uses: actions/setup-node@v3
    - run: npm ci
    - run: npm run build --if-present
    - name: Subir artefacto
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: ./dist
    - name: Despliegue de la app
      uses: actions/deploy-pages@v4.0.5
